server:
  port: 8080

spring:
  application:
    name: frog_ai
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${frog.ai.openai.api-key}
      base-url: ${frog.ai.openai.base-url} #https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: ${frog.ai.chat.model} #qwen-max
    vectorstore:
      redis:
        initialize-schema: true # 是否初始化向量库索引结构
        prefix: "doc:"
        index-name: frog_ai_index
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.ai.chat.advisors: DEBUG
