server:
  port: 8080

spring:
  application:
    name: frog_ai
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${frog.ai.openai.api-key}
      base-url: ${frog.ai.openai.base-url} #https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: ${frog.ai.chat.model} #qwen-max
